/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--primary)",
        "primary-hover": "var(--primary-hover)",
        "primary-soft": "var(--primary-soft)",
        background: "var(--background)",
        surface: "var(--surface)",
        "surface-subtle": "var(--surface-subtle)",
        "surface-muted": "var(--surface-muted)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        success: "var(--success)",
        warning: "var(--warning)",
        danger: "var(--danger)",
        focus: "var(--focus)",
        "State-Layers-On-Surface-Opacity-12": "var(--focus)",
        "Schemes-Surface": "var(--surface)",
        "Schemes-Primary": "var(--primary)",
        "Schemes-On-Primary": "var(--surface)",
        "Icon-Default-Default": "var(--text-primary)",
        "Border-Default-Default": "var(--border)",
        "Text-Default-Secondary": "var(--text-secondary)",
        "Fills-Tertiary": "var(--surface-muted)",
        "Colors-Blue": "var(--primary)",
        gray: {
          "50": "var(--surface-subtle)",
          "100": "var(--surface-muted)",
          "200": "var(--border)",
          "300": "var(--border-strong)",
          "400": "var(--text-muted)",
          "500": "var(--text-secondary)",
          "600": "var(--text-secondary)",
          "700": "var(--text-primary)",
          "800": "var(--text-primary)",
          "900": "var(--text-primary)",
        },
        slate: {
          "300": "var(--text-secondary)",
          "400": "var(--text-secondary)",
          "500": "var(--text-muted)",
          "600": "var(--text-muted)",
          "700": "var(--border-strong)",
          "800": "var(--border)",
          "900": "var(--text-primary)",
          "950": "var(--text-primary)",
        },
        blue: {
          "400": "var(--primary)",
          "600": "var(--primary)",
          "700": "var(--primary-hover)",
          "900": "var(--primary)",
        },
        purple: {
          "400": "var(--primary)",
          "600": "var(--primary)",
          "900": "var(--primary)",
        },
        pink: { "400": "var(--primary)", "500": "var(--primary)" },
        cyan: { "400": "var(--primary)", "900": "var(--primary)" },
        emerald: {
          "300": "var(--success)",
          "400": "var(--success)",
          "500": "var(--success)",
          "900": "var(--success)",
        },
        green: {
          "100": "color-mix(in srgb, var(--success) 12%, white)",
          "300": "var(--success)",
          "400": "var(--success)",
          "500": "var(--success)",
          "600": "var(--success)",
          "700": "var(--success)",
          "800": "var(--success)",
        },
        yellow: {
          "50": "color-mix(in srgb, var(--warning) 8%, white)",
          "100": "color-mix(in srgb, var(--warning) 12%, white)",
          "300": "var(--warning)",
          "400": "var(--warning)",
          "500": "var(--warning)",
          "600": "var(--warning)",
          "700": "var(--warning)",
          "800": "var(--warning)",
          "900": "var(--warning)",
          "950": "var(--warning)",
        },
        red: {
          "100": "color-mix(in srgb, var(--danger) 10%, white)",
          "300": "var(--danger)",
          "400": "var(--danger)",
          "500": "var(--danger)",
          "600": "var(--danger)",
          "700": "var(--danger)",
          "800": "var(--danger)",
          "900": "var(--danger)",
          "950": "var(--danger)",
        },
        white: "var(--surface)",
        black: "var(--text-primary)",
        cadetblue: {
          "100": "var(--primary)",
          "200": "var(--primary)",
          "300": "var(--primary)",
          "400": "var(--primary)",
          "500": "var(--primary)",
        },
        cornflowerblue: {
          "100": "var(--primary)",
          "200": "var(--primary)",
        },
        mediumblue: "var(--primary)",
        mediumslateblue: "var(--primary)",
        dimgray: { "100": "var(--text-secondary)", "200": "var(--surface-muted)" },
        steelblue: "var(--primary)",
        darkslategray: {
          "100": "var(--text-primary)",
          "200": "var(--text-primary)",
        },
        mistyrose: "color-mix(in srgb, var(--danger) 10%, white)",
        firebrick: {
          "100": "var(--danger)",
          "200": "var(--danger)",
        },
        darkgray: {
          "100": "var(--text-muted)",
          "200": "var(--surface-muted)",
          "300": "var(--surface-muted)",
        },
        aliceblue: "var(--primary-soft)",
        silver: "var(--border-strong)",
        slategray: "var(--text-secondary)",
      },
      spacing: {
        "Space-200": "8px",
        "Space-400": "16px",
        "Space-300": "12px",
        "Depth-100": "4px",
        "Depth-0": "0px",
        "Depth-025": "1px",
        "Padding-sm": "8px",
      },
    fontFamily: {
      // This sets 'Roboto' as the default font for your entire website.
      // Any text element will now use Roboto automatically.
      sans: ['DM Sans', 'Arial', 'sans-serif'],

      // (Optional) You can keep a second font for special, large headings.
      // To use it, you would add the class "font-display" to a heading element.
      display: ['Lora', 'Georgia', 'serif'],
    },

      borderRadius: {
        "Radius-200": "8px",
        "Radius-Full": "9999px",
        "31xl": "50px",
        mini: "15px",
        "81xl": "100px",
        "4xl": "23px",
        "3xs": "10px",
        "21xl": "40px",
        xl: "20px",
        "11xl": "30px",
        "41xl": "60px",
        "9980xl": "9999px",
        "71xl": "90px",
        "8xs": "5px",
      },
      borderWidth: {
        "Stroke-Border": "1px",
      },
      padding: {
        "44xl": "63px",
        "336xl": "355px",
        "87xl": "106px",
        "259xl": "278px",
        "791xl": "810px",
        "118xl": "137px",
        "351xl": "370px",
        "610xl": "629px",
        "4xs": "9px",
        "585xl": "604px",
        "693xl": "712px",
        "6xs": "7px",
        "2xs": "11px",
        "125xl": "144px",
        "55xl": "74px",
        "54xl": "73px",
        "17xl": "36px",
        "18xl": "37px",
        "181xl": "200px",
        "111xl": "130px",
        "85xl": "104px",
        "92xl": "111px",
        "48xl-1": "67.1px",
        "65xl": "84px",
        xl: "20px",
        "23xl": "42px",
        "36xl": "55px",
        "12xs": "1px",
        "168xl": "187px",
        "xs-4": "11.4px",
        "273xl": "292px",
        "60xl": "79px",
        "12xl": "31px",
        "21xl": "40px",
        "48xl": "67px",
        lgi: "19px",
        "4xl": "23px",
        "25xl": "44px",
        "10xl": "29px",
        "10xs": "3px",
        "11xl": "30px",
        "94xl": "113px",
        smi: "13px",
        mini: "15px",
        "30xl": "49px",
        "32xl": "51px",
        "100xl": "119px",
        "2xl": "21px",
        "31xl": "50px",
        "13xl": "32px",
        "16xl": "35px",
        "33xl": "52px",
        "42xl": "61px",
        "195xl": "214px",
        "200xl": "219px",
        "90xl": "109px",
        "88xl": "107px",
        "47xl": "66px",
        "187xl": "206px",
        "84xl": "103px",
        "14xl": "33px",
        "24xl": "43px",
        "229xl": "248px",
        "225xl": "244px",
        "103xl": "122px",
        "105xl": "124px",
        "2528xl-5": "2547.5px",
        "3288xl": "3307px",
        "1637xl": "1656px",
        "1057xl": "1076px",
        "1634xl": "1653px",
        "680xl": "699px",
        "62xl": "81px",
        "7xl": "26px",
        "3xs": "10px",
        "19xl": "38px",
        sm: "14px",
        "2542xl-5": "2561.5px",
        "20xl": "39px",
        "9xl": "28px",
        "37xl": "56px",
        "79xl": "98px",
        "45xl": "64px",
        "211xl": "230px",
        "38xl": "57px",
        "96xl": "115px",
        "40xl": "59px",
        "6xl": "25px",
        mid: "17px",
        lg: "18px",
        "165xl": "184px",
        "8xs": "5px",
        "59xl": "78px",
        "156xl": "175px",
        "lgi-9": "19.9px",
        "mini-7": "14.7px",
        "358xl": "377px",
        "270xl": "289px",
        "169xl": "188px",
        "210xl": "229px",
        "209xl": "228px",
        "95xl": "114px",
      },

      // --- ADDED FOR ANIMATED BACKGROUND ---
      animation: {
        'gradient-xy': 'gradient-xy 15s ease infinite',
      },
      keyframes: {
        'gradient-xy': {
          '0%, 100%': {
            'background-size': '400% 400%',
            'background-position': 'left center',
          },
          '50%': {
            'background-size': '200% 200%',
            'background-position': 'right center',
          },
        },
      },
      // --- END OF ADDED CODE ---

    },
    // --- Your other theme properties outside of 'extend' ---
    fontWeight: {
      thin: "100", extralight: "200", light: "300", normal: "400", medium: "500", semibold: "600", bold: "700", extrabold: "800", black: "900",
      "Body-Font-Weight-Regular": "400",
      "Body-Font-Weight-Strong": "600",
    },
    fontSize: {
      "Body-Size-Medium": "1.125rem",
      "Display-Large-Size": "3.688rem",
      mini: "1.063rem",
      mid: "1.188rem",
      base: "1.125rem",
      "38xl": "3.688rem",
      sm: "1rem",
      "17xl": "2.375rem",
      "3xl": "1.5rem",
      "10xl": "1.938rem",
      "5xl": "1.625rem",
      lgi: "1.313rem",
      lg: "1.25rem",
      xs: "0.875rem",
      "29xl": "3.125rem",
      "19xl": "2.5rem",
      "8xl": "1.813rem",
      xl: "1.375rem",
      "6xl": "1.688rem",
      "16xl": "2.313rem",
      "4xl": "1.563rem",
      "11xl": "2rem",
      "7xl": "1.75rem",
      "2xl": "1.438rem",
      inherit: "inherit",
    },
    screens: {
      sm: "640px", md: "768px", xl: "1280px", "2xl": "1536px",
      mq1325: {
        raw: "screen and (max-width: 1325px)",
      },
      lg: "1024px",
      mq1125: {
        raw: "screen and (max-width: 1125px)",
      },
      mq1100: {
        raw: "screen and (max-width: 1100px)",
      },
      mq1050: {
        raw: "screen and (max-width: 1050px)",
      },
      mq1025: {
        raw: "screen and (max-width: 1025px)",
      },
      mq800: {
        raw: "screen and (max-width: 800px)",
      },
      mq750: {
        raw: "screen and (max-width: 750px)",
      },
      mq675: {
        raw: "screen and (max-width: 675px)",
      },
      mq450: {
        raw: "screen and (max-width: 450px)",
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
};
